name: address_book
description: A personal address book.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.2.8+4
  go_router: ^9.0.3
  flutter_bloc: ^8.1.3
  path: ^1.8.3
  shared_preferences: ^2.2.0
  http: ^1.1.0
  mask_text_input_formatter: ^2.5.0
  collection: ^1.17.1
  loading_animation_widget: ^1.2.0+4
  google_fonts: ^5.1.0
  flutter_native_splash: ^2.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  

flutter:
  uses-material-design: true


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"
  adaptive_icon_background: "#E4BABD"
  adaptive_icon_foreground: "assets/logo.png"
  min_sdk_android: 21

flutter_native_splash:
  color: "#E4BABD"